on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: '106.54.68.249'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './doc/*'
          remote_path: '/home/doc'
          args: '-o ConnectTimeout=5'
